import{a as P,i as v,S as q}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const x="https://pixabay.com/api/",E="44085737-801aedd726c9c1496368a8656";async function y(e,t=1){const a={key:E,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await P.get(x,{params:a})).data}catch(i){throw i}}function M({webformatURL:e,largeImageURL:t,tags:a,likes:i,views:r,comments:o,downloads:s}){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${t}">
        <img class="gallery-image" src="${e}" alt="${a}"/>
      </a>
      <ul class="info">
        <li class="info-item"> <b>Likes</b> ${i} </li>
        <li class="info-item"> <b>Views</b> ${r} </li>
        <li class="info-item"> <b>Comments</b> ${o} </li>
        <li class="info-item"> <b>Downloads</b> ${s} </li>
      </ul>
    </li>
  `}function $(e){return e.map(M).join("")}const g=document.querySelector(".search-form"),u=document.querySelector(".gallery"),m=document.querySelector(".loader"),n=document.createElement("button");n.textContent="Load more";n.classList.add("load-more");u.parentNode.insertBefore(n,u.nextSibling);n.style.display="none";const p=document.createElement("div");p.appendChild(m);n.parentNode.insertBefore(p,n.nextSibling);let d="",c=1,h=0;g.addEventListener("input",e=>{d=e.target.value.trim()});g.addEventListener("submit",A);n.addEventListener("click",B);async function A(e){if(e.preventDefault(),c=1,u.innerHTML="",n.style.display="none",w(),!d){l("Please enter a search query!","blue"),f();return}try{const t=await y(d,c);if(h=t.totalHits,t.hits.length===0){l("Sorry, there are no images matching your search query. Please try again!","red");return}b(t.hits),S.refresh(),L()}catch(t){l("An error occurred while fetching images. Please try again later.","orange"),console.error(t)}finally{f()}e.target.reset()}async function B(){c+=1,w();try{const e=await y(d,c);b(e.hits),S.refresh(),C(),L()}catch(e){l("An error occurred while fetching images. Please try again later.","orange"),console.error(e)}finally{f()}}function b(e){const t=$(e);u.insertAdjacentHTML("beforeend",t)}function L(){c*15>=h?(n.style.display="none",l("We're sorry, but you've reached the end of search results.","blue")):n.style.display="block"}function C(){const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}function w(){m.style.display="inline-block"}function f(){m.style.display="none"}function l(e,t){v.info({position:"topRight",timeout:1800,maxWidth:300,icon:"none",message:e,backgroundColor:t})}let S=new q(".gallery a",{captionDelay:250,captionsData:"alt"});
//# sourceMappingURL=commonHelpers.js.map
